---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: db
spec:
  containers:
    - name: mysqlartifactory
      image: mattsmanoj.jfrog.io/docker-local/mysql:8.0
      ports:
        - containerPort: 3306
          protocol: TCP